resources:
  - apiVersion: platform.confluent.io/v1beta1
    kind: KRaftController
    metadata:
      name: kraftcontroller
      namespace: confluent
    spec:
      dataVolumeCapacity: 1Gi
      image:
        application: docker.io/confluentinc/cp-server:7.6.0
        init: confluentinc/confluent-init-container:2.8.0
      replicas: 1
  - apiVersion: platform.confluent.io/v1beta1
    kind: Kafka
    metadata:
      name: kafka
      namespace: confluent
    spec:
      replicas: 1
      image:
        application: confluentinc/cp-server:7.6.0
        init: confluentinc/confluent-init-container:2.8.0
      dataVolumeCapacity: 100Gi
      dependencies:
        kRaftController:
          clusterRef:
            name: kraftcontroller
